# Generated by Django 5.2.3 on 2025-06-11 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100, unique=True, verbose_name='Question key')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'question_key'],
            },
        ),
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cancer type name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_organ', models.BooleanField(default=False, help_text='If checked, this cancer type represents an organ-level classification', verbose_name='Is organ-level type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='medical.cancertype', verbose_name='Parent cancer type')),
            ],
            options={
                'verbose_name': 'Cancer type',
                'verbose_name_plural': 'Cancer types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAssignmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Processed by')),
            ],
            options={
                'verbose_name': 'Doctor assignment request',
                'verbose_name_plural': 'Doctor assignment requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='medical.faq', verbose_name='FAQ')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_translations', to='accounts.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'FAQ translation',
                'verbose_name_plural': 'FAQ translations',
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document title')),
                ('document_type', models.CharField(max_length=100, verbose_name='Document type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('patient_notes', models.TextField(blank=True, help_text='Additional notes that will be visible to the patient', verbose_name='Notes for patient')),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/%d/', verbose_name='File')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='File hash')),
                ('recommended_treatment', models.TextField(blank=True, help_text='Treatment recommendations extracted from document', verbose_name='Recommended treatment')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from the document using OCR', verbose_name='Extracted text')),
                ('is_pathology_report', models.BooleanField(default=False, help_text='Indicates if the document was detected as a pathology report', verbose_name='Is pathology report')),
                ('ai_analysis_json', models.JSONField(blank=True, help_text='Results of AI analysis of the document', null=True, verbose_name='AI analysis results')),
                ('analysis_timestamp', models.DateTimeField(blank=True, help_text='When the document was last analyzed by AI', null=True, verbose_name='Analysis timestamp')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('cancer_type', models.ForeignKey(blank=True, limit_choices_to={'is_organ': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medical.cancertype', verbose_name='Cancer type')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_documents', to='accounts.language', verbose_name='Language')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Medical document',
                'verbose_name_plural': 'Medical documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')], verbose_name='Rating')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient feedback',
                'verbose_name_plural': 'Patient feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_stage_text', models.CharField(blank=True, help_text='Stage of cancer (e.g., Stage I, Stage II, etc.)', max_length=50, verbose_name='Cancer stage')),
                ('diagnosis_date', models.DateField(blank=True, null=True, verbose_name='Diagnosis date')),
                ('stage_grouping', models.CharField(blank=True, max_length=100, verbose_name='Stage grouping')),
                ('recommended_treatment', models.TextField(blank=True, verbose_name='Recommended treatment')),
                ('vital_status', models.BooleanField(default=True, verbose_name='Active patient')),
                ('notes', models.TextField(blank=True, verbose_name='Medical notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cancer_type', models.ForeignKey(blank=True, limit_choices_to={'is_organ': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='medical.cancertype', verbose_name='Cancer type')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Patient record',
                'verbose_name_plural': 'Patient records',
            },
        ),
        migrations.CreateModel(
            name='ClinicianReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Review date')),
                ('notes', models.TextField(verbose_name='Review notes')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Clinician')),
                ('patient_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_reviews', to='medical.patientrecord', verbose_name='Patient record')),
            ],
            options={
                'verbose_name': 'Clinician review',
                'verbose_name_plural': 'Clinician reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='cancertype',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_name_parent'),
        ),
        migrations.AlterUniqueTogether(
            name='faqtranslation',
            unique_together={('faq', 'language')},
        ),
    ]
