# Generated by Django 5.2.1 on 2025-05-10 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_complete_cancer_stage_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='cancer_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='medical.patientrecord', verbose_name='Cancer stage (DEPRECATED)'),
        ),
    ]
