# Generated by Django 5.2.1 on 2025-05-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_remove_patientrecord_cancer_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='recommended_treatment',
            field=models.TextField(blank=True, help_text='Treatment recommendations extracted from document', verbose_name='Recommended treatment'),
        ),
    ]
