# Generated by Django 5.2.3 on 2025-06-11 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='User ID')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='User email')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10, verbose_name='Action')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model name')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object ID')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
            ],
            options={
                'verbose_name': 'Audit log archive',
                'verbose_name_plural': 'Audit log archives',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name'], name='audit_audit_model_n_831717_idx'), models.Index(fields=['action'], name='audit_audit_action_75f18d_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_d59ba3_idx'), models.Index(fields=['user_id'], name='audit_audit_user_id_070970_idx'), models.Index(fields=['user_email'], name='audit_audit_user_em_27448e_idx'), models.Index(fields=['object_id'], name='audit_audit_object__c07d23_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10, verbose_name='Action')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model name')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object ID')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Changes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name'], name='audit_audit_model_n_515731_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['object_id'], name='audit_audit_object__9f698d_idx')],
            },
        ),
    ]
