# Generated by Django 5.2.1 on 2025-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_model_n_515731_idx',
            old_name='audit_audit_model_n_d78a34_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_86e815_idx',
            old_name='audit_audit_action_6a83da_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_timesta_19e18a_idx',
            old_name='audit_audit_timesta_5be65c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_292c79_idx',
            old_name='audit_audit_user_id_2d811d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_object__9f698d_idx',
            old_name='audit_audit_object__9d7cc9_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogarchive',
            new_name='audit_audit_model_n_831717_idx',
            old_name='audit_audit_model_n_ec11a5_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogarchive',
            new_name='audit_audit_action_75f18d_idx',
            old_name='audit_audit_action_c51515_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogarchive',
            new_name='audit_audit_timesta_d59ba3_idx',
            old_name='audit_audit_timesta_1b7686_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogarchive',
            new_name='audit_audit_user_id_070970_idx',
            old_name='audit_audit_user_id_9b9a36_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogarchive',
            new_name='audit_audit_user_em_27448e_idx',
            old_name='audit_audit_user_em_d4c3b7_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogarchive',
            new_name='audit_audit_object__c07d23_idx',
            old_name='audit_audit_object__6db1d1_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
    ]
