# Generated by Django 5.2.3 on 2025-06-11 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, limit_choices_to={'code': 'en'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.language', verbose_name='Preferred language'),
        ),
    ]
