# Generated by Django 5.2.1 on 2025-05-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_specialty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, default='en', limit_choices_to={'code': 'en'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.language', verbose_name='Preferred language'),
        ),
    ]
