# Generated by Django 5.2.1 on 2025-05-08 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('medical', '0002_cancerstage_cancertype_faq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat document', 'verbose_name_plural': 'Chat documents'},
        ),
        migrations.AlterModelOptions(
            name='chatdocumentchunk',
            options={'ordering': ['document', 'chunk_index'], 'verbose_name': 'Document chunk', 'verbose_name_plural': 'Document chunks'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat message', 'verbose_name_plural': 'Chat messages'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chat session', 'verbose_name_plural': 'Chat sessions'},
        ),
        migrations.AddField(
            model_name='chatdocument',
            name='cancer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_documents', to='medical.cancertype', verbose_name='Cancer type'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='document_type',
            field=models.CharField(max_length=100, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='file',
            field=models.FileField(upload_to='chat_documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='indexed',
            field=models.BooleanField(default=False, verbose_name='Indexed in vector store'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Indexed at'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Document title'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='chatdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_chat_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AlterField(
            model_name='chatdocumentchunk',
            name='chunk_index',
            field=models.IntegerField(verbose_name='Chunk index'),
        ),
        migrations.AlterField(
            model_name='chatdocumentchunk',
            name='content',
            field=models.TextField(verbose_name='Chunk content'),
        ),
        migrations.AlterField(
            model_name='chatdocumentchunk',
            name='embedding_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Embedding ID in vector store'),
        ),
        migrations.AlterField(
            model_name='chatdocumentchunk',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatdocumentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='chatfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='chatfeedback',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='Message content'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Chat session'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Session title'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterUniqueTogether(
            name='chatdocumentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
