# Generated by Django 4.1.13 on 2025-01-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_ragmetrics'),
        ('chat', '0004_limit_cancer_type_to_organs'),
    ]

    operations = [
    ]