# Generated by Django 5.2.1 on 2025-05-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20250117_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAGMetrics',
        ),
    ]
